// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: epavpfqdzlgbkhwibotb

class SupabaseConfig {
  static const String supabaseUrl = 'https://epavpfqdzlgbkhwibotb.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwYXZwZnFkemxnYmtod2lib3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMDU2MTcsImV4cCI6MjA3Njg4MTYxN30.0G1r69D0pcPX4aW7OS_6X07LBMPy2btCL4KpIdcmfy0';
}
